l_gerase:
    resource: "@LGeraseBundle/Resources/config/routing.yml"
    prefix:   /

test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /

loic_platform:
    resource: "@loicPlatformBundle/Resources/config/routing.yml"
    prefix:   /
